### ISSUE TITLE
How to use this with ngFor?

### ISSUE THREAD

**Issue by rastographics** [filipows/angular-animations#30]
I have an ngFor displaying the items in my array. How can display animations onEnter and onLeave every time an element is added or removed from my array?

` <mat-card [@bounceInOnEnter] [@bounceOutOnLeave] *ngFor="let file of audioFiles">`

My component that contains the <mat-card> items is setup like so:

`@Component({
  selector: 'app-main-form',
  templateUrl: './main-form.component.html',
  styleUrls: ['./main-form.component.scss'],
  animations:[
    bounceInOnEnterAnimation,
    bounceOutOnLeaveAnimation
  ]
})`

Currently I get the error:

`Error: Uncaught (in promise): Error: Unable to resolve animation metadata node #undefined`

**Comment by filipows** [comment]
Hi @rastographics,

I think you missed parenthesis at the end of functions that declare animations:

Instead of 
```typescript
@Component({
  selector: 'app-main-form',
  templateUrl: './main-form.component.html',
  styleUrls: ['./main-form.component.scss'],
  animations: [
    bounceInOnEnterAnimation, 
    bounceOutOnLeaveAnimation
  ]
})
```
should be 
```typescript
@Component({
  selector: 'app-main-form',
  templateUrl: './main-form.component.html',
  styleUrls: ['./main-form.component.scss'],
  animations: [
    bounceInOnEnterAnimation(), 
    bounceOutOnLeaveAnimation()
  ]
})
```

I also created a simple example with *ngFor for you on Stackblitz
[*ngFor Example on Stackblitz](https://stackblitz.com/edit/angular-animations-lib-ng-for-example?file=src%2Fapp%2Fdemo-main%2Fdemo-main.component.html)

Let me know if that helps.

**Comment by rastographics** [comment]
Thank you that was my problem
