### ISSUE TITLE
animation going left

### ISSUE THREAD

**Issue by TaiyouFTW** [filipows/angular-animations#51]
Hello i have a doubt, the standard animation pulse/rubber going left is normal?

this is my stackblit test, can you tell if I'm forgetting something?

https://stackblitz.com/edit/taiyou-test-angular-animations

thanks for the help

**Comment by filipows** [comment]
Hi @TaiyouFTW ,

It only looks like it's going left, because you are applying pulse animation on a block element (`<div>`) which by default has 100% width.

If you want to apply the pulse animation in this case, maybe you could add:
`display: inline-block` to the element.

Here's [StackBlitz example](https://stackblitz.com/edit/taiyou-test-angular-animations-l1wdz3?file=src/app/app.component.html)

**Comment by TaiyouFTW** [comment]
Thank you so much @filipows
